#!/bin/bash
#SBATCH -p skx-dev
#SBATCH -J pycis.job
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -o pycis.out

# #SBATCH --mail-user 
# #SBATCH --mail-type ALL

# Switch to folder and load modules
module load gcc/9.1
module load python3/3.8.2

# Check installation and activate source 
source env/bin/activate

#set omp and run demo with faulthandler
export OMP_NUM_THREADS=48
python3 -q -X faulthandler demo.py

#close source for safe exit
deactivate
